# Generated by Django 5.1.4 on 2025-02-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_manager', '0003_alter_customuser_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания чата')),
                ('dt_last_message', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего сообщения')),
                ('first_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_user', to='profile_manager.customuser', verbose_name='Первый пользователь')),
                ('second_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_user', to='profile_manager.customuser', verbose_name='Второй пользователь')),
            ],
            options={
                'verbose_name': 'Сессия чата',
                'verbose_name_plural': 'Сессии чата',
                'unique_together': {('first_user', 'second_user')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст сообщения')),
                ('dt_send', models.DateTimeField(auto_now=True, verbose_name='Дата и время отправки')),
                ('is_received', models.BooleanField(default=False, verbose_name='Получено')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession', verbose_name='Сессия чата')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_manager.customuser', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
