# Generated by Django 5.1.4 on 2025-02-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('profile_manager', '0003_alter_customuser_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='first_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions_created', to='profile_manager.customuser', verbose_name='Первый пользователь'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='second_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions_invited', to='profile_manager.customuser', verbose_name='Второй пользователь'),
        ),
    ]
