# Generated by Django 5.1.4 on 2025-02-23 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatsession_first_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='first_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Первый пользователь'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='second_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions_invited', to=settings.AUTH_USER_MODEL, verbose_name='Второй пользователь'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
