# Generated by Django 5.1.4 on 2025-03-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatsession_first_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='uuid',
            field=models.UUIDField(default=1, verbose_name='Уникальный идентификатор сессии чата'),
            preserve_default=False,
        ),
    ]
