# Generated by Django 5.1.4 on 2025-02-09 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dt_birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profile_manager.town', verbose_name='Город'),
        ),
    ]
