# Generated by Django 5.1.4 on 2025-02-09 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0002_alter_customuser_dt_birthday_alter_customuser_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profile_manager.town', verbose_name='Город'),
        ),
    ]
