# Generated by Django 5.1.4 on 2025-02-23 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatsession_first_user_and_more'),
        ('education', '0002_alter_lesson_creator_alter_lesson_listeners'),
        ('profile_manager', '0004_alter_customuser_dt_birthday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Адрес')),
                ('image', models.ImageField(default='profile_images/default.png', upload_to='profile_images/', verbose_name='Изображение')),
                ('dt_birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('status', models.CharField(blank=True, max_length=150, verbose_name='Статус')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profile_manager.town', verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информации о пользователях',
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_manager.userinformation', verbose_name='Информация о пользователе'),
        ),
        migrations.AlterField(
            model_name='interestingfact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_manager.userinformation', verbose_name='Информация о пользователе'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
