# Generated by Django 5.1.4 on 2025-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0005_userinformation_alter_education_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(default='', max_length=150, verbose_name='Учебное заведение'),
        ),
    ]
