# Generated by Django 5.1.4 on 2025-06-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0006_education_university'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
