# Generated by Django 5.1.4 on 2025-02-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_manager', '0003_alter_customuser_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название урока')),
                ('difficulty', models.IntegerField(choices=[('Низкая', 1), ('Ниже среднего', 2), ('Средняя', 3), ('Выше среднего', 4), ('Высокая', 5)], verbose_name='Сложность')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания урока')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования урока')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to='profile_manager.customuser', verbose_name='Создатель')),
                ('listeners', models.ManyToManyField(related_name='opened_lessons', to='profile_manager.customuser', verbose_name='Слушатели')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название теста')),
                ('number', models.IntegerField(verbose_name='Порядковый номер')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания теста')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования теста')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'unique_together': {('name', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='TestPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='Контент вопроса теста')),
                ('number', models.IntegerField(verbose_name='Порядковый номер')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Часть теста',
                'verbose_name_plural': 'Части теста',
                'unique_together': {('test', 'content')},
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название лекции')),
                ('number', models.IntegerField(verbose_name='Порядковый номер')),
                ('content', models.CharField(max_length=5000, verbose_name='Контент лекции')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания лекции')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования лекции')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'unique_together': {('name', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='Контент вопроса ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('test_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.testpart', verbose_name='Часть теста')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'unique_together': {('test_part', 'content')},
            },
        ),
    ]
