# Generated by Django 5.1.4 on 2025-03-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_lesson_creator_alter_lesson_listeners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('Низкая', 1), ('Ниже среднего', 2), ('Средняя', 3), ('Выше среднего', 4), ('Высокая', 5)], verbose_name='Сложность'),
        ),
    ]
