# Generated by Django 5.1.4 on 2025-03-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_lesson_difficulty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='test',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Низкая'), (2, 'Ниже'), (3, 'Средняя'), (4, 'Выше'), (5, 'Высокая')], verbose_name='Сложность'),
        ),
        migrations.CreateModel(
            name='LessonPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название части урока')),
                ('number', models.IntegerField(verbose_name='Порядковый номер')),
                ('content', models.CharField(blank=True, max_length=5000, verbose_name='Контент части урока')),
                ('type', models.CharField(choices=[('TEST', 'Тест'), ('LECTURE', 'Лекция')], max_length=7, verbose_name='Тип части урока')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания части урока')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования части урока')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Часть урока',
                'verbose_name_plural': 'Части уроков',
                'unique_together': {('lesson', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='testpart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testpart',
            name='lesson_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.lessonpart', verbose_name='Часть урока'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='testpart',
            unique_together={('lesson_part', 'content')},
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.RemoveField(
            model_name='testpart',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
