# Generated by Django 5.1.4 on 2025-06-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_test_unique_together_remove_test_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Очень легко'), (2, 'Достаточно легко'), (3, 'Нормально'), (4, 'Достаточно сложно'), (5, 'Очень сложно')], verbose_name='Сложность'),
        ),
    ]
