# Generated by Django 5.1.4 on 2025-06-02 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_lesson_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание урока'),
        ),
        migrations.AlterField(
            model_name='lessonpart',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='education.lesson', verbose_name='Урок'),
        ),
    ]
