# Generated by Django 5.1.4 on 2025-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_lesson_description_alter_lessonpart_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpart',
            name='image',
            field=models.ImageField(null=True, upload_to='lesson_images/', verbose_name='Изображение'),
        ),
    ]
